### PR TITLE
Added GeoJSON editor

### PR DESCRIPTION
**Pull request by tomscholz**

### CODE REVIEW

**Comment by tmcw** [comment]
Could you remove the link to Google's original editor? It's causing tests to fail because they think of it as a duplicate link.

**Comment by tomscholz** [comment]
I don't get it 😴  Have to sleep now ;) Were you able to resolve the problem?

**Comment by tomscholz** [comment]
You could rewrite the test so that it allows redirects like here `--allow-redirect` https://github.com/dkhamsing/awesome_bot

**Comment by tomscholz** [comment]
Thanks :)

**Pull request merged**
